on: [push]

name: Datadog Static Analysis

permissions:
  contents: read
  pull-requests: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: Datadog Static Analyzer
    steps:
    - name: Get Datadog credentials
      id: dd-sts
      uses: DataDog/dd-sts-action@2e8187910199bd93129520183c093e19aa585c75
      with:
        policy: dd-trace-go
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Check code meets quality and security standards
      id: datadog-static-analysis
      uses: DataDog/datadog-static-analyzer-github-action@8340f18875fcefca86844b5f947ce2431387e552 # v3.0.0
      with:
        dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
        dd_app_key: ${{ steps.dd-sts.outputs.app_key }}
        dd_service: dd-trace-go
        dd_env: ci
        dd_site: datadoghq.com
        cpu_count: 2
